### ISSUE TITLE
load_veldwerk_json afmaken

### ISSUE THREAD

**Issue by bastiaan-roos** [tijhuisingenieurs/TijhuisArcGisTools#67]
load_veldwerk_json
- [x] meetplan shape meegeven (profile lijnen) vanuit arcgis als memcollection. profile id is DWPcode?
- [x] meetplan shape opgeven testen
- [x] test toevoegen voor profiel informatie
- [x] Voor de tool load_veldwerk_json in arcgis de volgende velden ondersteunen:
   - breedte
   - h_breedte
   - gps_breed
   - m99_breed
- [x] Nakijken vulling berekende attributeb

**Comment by bastiaan-roos** [comment]
zie bastiaan-tool_c branch

**Comment by AnnemiekeVogel** [comment]
in pull request #37 Bastiaan tool c

**Comment by AnnemiekeVogel** [comment]
in pull reuest tijhuisingenieurs/gistools#39 Bastiaan tool c

**Comment by AnnemiekeVogel** [comment]
alle mogelijke berekeningen lijken te werken. Er doet zich nog één issue voor, en dat zijn punten waarbij de methode op manual staat en de waarde tot in mNAP is uitgedrukt. Deze worden nu niet doorgerekend omdat de combinatie niet klopt. Wanneer de app aangepast is zodat bij handmatige hoogte in water altijd cm tov WP wordt gebruikt, is dit geen probleem. Anders alsnog code uitbreiden om deze situaties te herkennen en door te rekenen (ervan uitgaande dat de nap hoogtes juist zijn).
