### ISSUE TITLE
create_veldwerk_output_shapes

### ISSUE THREAD

**Issue by bastiaan-roos** [tijhuisingenieurs/TijhuisArcGisTools#68]
volgende punten om deze af te maken:
- [x] TLine.get_projected_point_at_distance functie maken die bij negatieve waarden of waarden voorbij het laatste punt als het ware 'doorstippeld'
- [x] omgang missende waarde point_props['bk_wp'] en point_props['ok_wp'] in berekening
- [x] Argis warpper om script (met support voor lezen uit csv tabel en memcolelction voor de punten)
- [x] Omzetten metfile en wdb scripts naar attributen uit output shapes

**Comment by bastiaan-roos** [comment]
ook in de bastiaan-tool_c branch

**Comment by AnnemiekeVogel** [comment]
TLine.get_projected_point_at_distance in pull request #37 Bastiaan tool c

**Comment by AnnemiekeVogel** [comment]
Omgang missing _wp waarden in pull request #37 Bastiaan tool c

**Comment by AnnemiekeVogel** [comment]
Export metfiles en wdb data in pull request tijhuisingenieurs/TijhuisArcGosTools#69 veld app arc gis

**Comment by AnnemiekeVogel** [comment]
Status 28-08-2017: tool wordt momenteel uitgebreid getest met echte velddata. Issue sluiten wanneer de basis 'waterdicht' is.
