### ISSUE TITLE
berekende waarden in .json data

### ISSUE THREAD

**Issue by AnnemiekeVogel** [tijhuisingenieurs/TijhuisArcGisTools#70]
wat is / wordt nu de waarde van het veld 'distance' bij punten met code 2?

Het zou het meest logisch zijn dat deze afstand uitgedrukt is t.o.v. 22L, want dan kan ik hem 1-op- overnemen in de verwerking. Ik zie nu bijvoorbeeld bij profiel 272 een GPS meetpunt code 2 met een afstand < de afstand van 22R, terwijl er ook een GPS meetpunt code 2 is met een afstand > 22R. De waarden in deze proefmeting zijn volgens mij berekend t.o.v. 22L, toch?

Dit zou in het profielplaatje denk ik ook al zichtbaar zijn geworden op de app?
Ruwe metingen direct door naar WDB = zie bijlage... ik zie bij meerdere profielen opvallende meetpunten als pieken in het natte deel.

[WDB_export_test_wdbdf.pdf](https://github.com/tijhuisingenieurs/TijhuisArcGisTools/files/1131074/WDB_export_test_wdbdf.pdf)

**Comment by bastiaan-roos** [comment]
in de app zit de onderstaande logica. De rechteroever punten worden berekend vanaf het punt 22R en daarbij wordt de breedte (handmatig of anders afstand tot 22L) bij opgeteld. Als er geen 22R punt is wordt er gerekend vanaf 22L.


if (point.code === '22L') {
   return 0.0;
 } else if (point.code === '22R' && manual_profile_width) {
   return Number(manual_profile_width);
 } else if (point.code === '2') {
  if (ttr) {
    if (manual_profile_width) {
      return calcDistanceBetween(point, ttr) + Number(manual_profile_width);
    } else if (ttl) {
      return (calcDistanceBetween(point, ttr) + calcDistanceBetween(ttl, ttr));
    } else {
      return null;
    }
  } else if (ttl) {
    return calcDistanceBetween(ttl, point);
  } else {
    return null;
  }
} else if (ttl) {
  let output = calcDistanceBetween(ttl, point);
  if (point.code === '1') {
    output = -1 * output;
  }
  return output;
} else {
  return null
}

**Comment by AnnemiekeVogel** [comment]
herberekening afstanden nu correct ingebouwd in laden velddata tool
