### ISSUE TITLE
Toolswens: Snap tool maken -> t.b.v. correctie op ontbrekende intersecties

### ISSUE THREAD

**Issue by AnnemiekeVogel** [tijhuisingenieurs/TijhuisArcGisTools#95]
Soms blijkt bij de hernummertool of andere tools, dat een op de lijnen gegenereerde puntenshape niet meer 100% intersectie heeft. Dit gebeurt meestal wanneer er één of meerdere punten in de shape zijn aangepast (met snap to edge optie aan). Het effect is dat ArcGIS nog steeds een intersectie vindt, maar de tools niet meer (voor meer dan alleen de aangepaste objecten ?!?)

In de ET Geowizard toolbox zit een snap points to lines, maar deze is weggestopt onder een licentie bij meer dan 100 punten.

Wens is dus om de snap points to lines tool in onze toolbox in te bouwen. Dit kan eenvoudig met de .project methode van shapely.

**Comment by elinevanelburg** [comment]
Added a tool that snaps points to the nearest line.
